# -*- coding: utf-8 -*-
"""Ozibook_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12oC2zmmwzYuwiZBzA3ERu5hX-dH457ld
"""

from google.colab import files 
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
Sales = pd.read_csv("vgsales.csv")
Sales

Sales.info()

Sales.describe()

Sales.isnull().sum()

Sales.shape

#droping all the nan values
Sales = Sales.dropna()

Sales.isnull().sum()

#changing data type of year from float to int 
Sales['Year'] = Sales['Year'].astype('int')

Sales.info()

Sales.shape

#finding all the unique values
TG = Sales['Genre'].unique()
TG.shape

TP = Sales['Publisher'].unique()
TP

TP.shape

TPl = Sales['Platform'].unique()

TPl

TPl.shape

Publishers_sales=Sales.groupby("Publisher")["Global_Sales"].sum().sort_values(ascending=False).head(10)
Publishers_sales.reset_index()
# we got the list of top 10 publishers

plt.figure(figsize=(20,5))
sns.barplot(x="Publisher",y="Global_Sales",data=Publishers_sales.reset_index())

Genre_sales=Sales.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False)
Genre_sales.reset_index()

plt.figure(figsize=(15,5))
sns.barplot(x="Genre",y="Global_Sales",data=Genre_sales.reset_index())

"""Most of the Global sales is from **Action, Sports, Shooter, Role-Playing and Platform**"""

Platform_sales=Sales.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False)
Platform_sales.reset_index()

plt.figure(figsize=(20,10))
sns.barplot(x="Platform",y="Global_Sales",data=Platform_sales.reset_index())

TY = Sales['Year'].unique()
TY

TY.shape

#lets see how our golbal sale is affected over the years
Year_sales=Sales.groupby("Year")["Global_Sales"].sum()
Year_sales.reset_index()

plt.figure(figsize=(20,10))
sns.barplot(x="Year",y="Global_Sales",data=Year_sales.reset_index())

"""After **2008** Global sells **decreased** drastically. """

Year_sales.plot(x='Year', y='Global_Sales' ,figsize=(10,5), grid=True)

TT = Sales[Sales['Genre']=="Sports"]
TT

TE = Sales[Sales['Year']>=2008]
TE
# getting the data after 2008

TE2 = Sales[Sales['Year']<2008]
TE2
# getting the data before 2008

Genre_salesY=TE.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False)
Genre_salesY.reset_index()
plt.figure(figsize=(15,5))
sns.barplot(x="Genre",y="Global_Sales",data=Genre_salesY.reset_index())

Genre_salesY2=TE2.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False)
Genre_salesY2.reset_index()
plt.figure(figsize=(15,5))
sns.barplot(x="Genre",y="Global_Sales",data=Genre_salesY2.reset_index())

"""From the above graphs we can clearly see that **Our Top Genre** i.e **Platform** and **Sports** decreased their revenue after 2008 as sports shifted from 2nd position to 3rd and Platform shifted from 3rd position to 7th."""

Platform_salesY=TE.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False)
Platform_salesY.reset_index()
plt.figure(figsize=(15,5))
sns.barplot(x="Platform",y="Global_Sales",data=Platform_salesY.reset_index())

Platform_salesY2=TE2.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False)
Platform_salesY2.reset_index()
plt.figure(figsize=(15,5))
sns.barplot(x="Platform",y="Global_Sales",data=Platform_salesY2.reset_index())

"""**After year 2008 out top platform PS2 stoped contributing to Global_Sales.**"""

Publishers_salesY=TE.groupby("Publisher")["Global_Sales"].sum().sort_values(ascending=False).head(10)
Publishers_salesY.reset_index()
plt.figure(figsize=(25,5))
sns.barplot(x="Publisher",y="Global_Sales",data=Publishers_salesY.reset_index())

Publishers_salesY2=TE2.groupby("Publisher")["Global_Sales"].sum().sort_values(ascending=False).head(10)
Publishers_salesY2.reset_index()
plt.figure(figsize=(25,5))
sns.barplot(x="Publisher",y="Global_Sales",data=Publishers_salesY2.reset_index())

"""**After 2008, Electronic Arts platform and Nintendo Golbal_Sales became equal and Sony Computer Entertainment left its top 3rd position.**"""

plt.figure(figsize=(19,10))
cor = Sales.corr()
sns.heatmap(cor, annot=True, cmap=plt.cm.CMRmap_r)
plt.show()

"""**Here we can see that JP_Sales, EU_Sales, NA_Sales and Other_Sales are highly corelated to Global_Sales i.e. more than 60% So whatever insight we get from Global_Sales is ultimately similar for all other.**"""

sns.pairplot(Sales)
plt.show()

